const mensajes = [
  {
    id: 1,
    asunto: 'Marble Cake',
    img: '/assets/img/marble-cake-thumb.jpg',
    category: 'Cakes',
    fecha_creacion: '02.04.2018',
    status: 'ON HOLD',
    statusColor: 'primary',
    description: 'Wedding cake with flowers Macarons and blueberries',
    sales: 1647,
    stock: 62,
  },
  {
    id: 2,
    asunto: 'Fat Rascal',
    category: 'Cupcakes',
    img: '/assets/img/fat-rascal-thumb.jpg',
    fecha_creacion: '01.04.2018',
    status: 'PROCESSED',
    statusColor: 'secondary',
    description: 'Cheesecake with chocolate cookies and Cream biscuits',
    sales: 1240,
    stock: 48,
  },
  {
    id: 3,
    asunto: 'Chocolate Cake',
    img: '/assets/img/chocolate-cake-thumb.jpg',
    category: 'Cakes',
    fecha_creacion: '25.03.2018',
    status: 'PROCESSED',
    statusColor: 'secondary',
    description: 'Homemade cheesecake with fresh berries and mint',
    sales: 1080,
    stock: 57,
  },
  {
    id: 4,
    asunto: 'Goose Breast',
    img: '/assets/img/goose-breast-thumb.jpg',
    category: 'Cakes',
    fecha_creacion: '21.03.2018',
    status: 'PROCESSED',
    statusColor: 'secondary',
    description: 'Chocolate cake with berries',
    sales: 1014,
    stock: 41,
  },
  {
    id: 5,
    asunto: 'Petit Gâteau',
    category: 'Cupcakes',
    img: '/assets/img/petit-gateau-thumb.jpg',
    fecha_creacion: '02.06.2018',
    status: 'ON HOLD',
    statusColor: 'primary',
    description: 'Chocolate cake with mascarpone',
    sales: 985,
    stock: 23,
  },
  {
    id: 6,
    asunto: 'Salzburger Nockerl',
    img: '/assets/img/salzburger-nockerl-thumb.jpg',
    category: 'Desserts',
    fecha_creacion: '14.07.2018',
    status: 'PROCESSED',
    statusColor: 'secondary',
    description: 'Wedding cake decorated with donuts and wild berries',
    sales: 962,
    stock: 34,
  },
  {
    id: 7,
    asunto: 'Napoleonshat',
    img: '/assets/img/napoleonshat-thumb.jpg',
    category: 'Desserts',
    fecha_creacion: '05.02.2018',
    status: 'PROCESSED',
    statusColor: 'secondary',
    description: 'Cheesecake with fresh berries and mint for dessert',
    sales: 921,
    stock: 31,
  },
  {
    id: 8,
    asunto: 'Cheesecake',
    img: '/assets/img/cheesecake-thumb.jpg',
    category: 'Cakes',
    fecha_creacion: '18.08.2018',
    status: 'ON HOLD',
    statusColor: 'primary',
    description: 'Delicious vegan chocolate cake',
    sales: 887,
    stock: 21,
  },
  {
    id: 9,
    asunto: 'Financier',
    img: '/assets/img/financier-thumb.jpg',
    category: 'Cakes',
    fecha_creacion: '15.03.2018',
    status: 'ON HOLD',
    statusColor: 'primary',
    description:
      'White chocolate strawberry yogurt cake decorated with fresh fruits and chocolate',
    sales: 865,
    stock: 53,
  },
  {
    id: 10,
    asunto: 'Genoise',
    img: '/assets/img/genoise-thumb.jpg',
    category: 'Cupcakes',
    fecha_creacion: '11.06.2018',
    status: 'PROCESSED',
    statusColor: 'secondary',
    description: 'Christmas fruit cake, pudding on top',
    sales: 824,
    stock: 55,
  },
  {
    id: 11,
    asunto: 'Gingerbread',
    img: '/assets/img/gingerbread-thumb.jpg',
    category: 'Cakes',
    fecha_creacion: '10.04.2018',
    status: 'ON HOLD',
    statusColor: 'primary',
    description: 'Wedding cake decorated with donuts and wild berries',
    sales: 714,
    stock: 12,
  },
  {
    id: 12,
    asunto: 'Magdalena',
    img: '/assets/img/magdalena-thumb.jpg',
    category: 'Cakes',
    fecha_creacion: '22.07.2018',
    status: 'PROCESSED',
    statusColor: 'secondary',
    description: 'Christmas fruit cake, pudding on top',
    sales: 702,
    stock: 14,
  },
  {
    id: 13,
    asunto: 'Parkin',
    img: '/assets/img/parkin-thumb.jpg',
    category: 'Cakes',
    fecha_creacion: '22.08.2018',
    status: 'ON HOLD',
    statusColor: 'primary',
    description:
      'White chocolate strawberry yogurt cake decorated with fresh fruits and chocolate',
    sales: 689,
    stock: 78,
  },
  {
    id: 14,
    asunto: 'Streuselkuchen',
    img: '/assets/img/streuselkuchen-thumb.jpg',
    category: 'Cakes',
    fecha_creacion: '22.07.2018',
    status: 'PROCESSED',
    statusColor: 'secondary',
    description: 'Delicious vegan chocolate cake',
    sales: 645,
    stock: 55,
  },
  {
    id: 15,
    asunto: 'Tea loaf',
    img: '/assets/img/tea-loaf-thumb.jpg',
    category: 'Cakes',
    fecha_creacion: '10.09.2018',
    status: 'ON HOLD',
    statusColor: 'primary',
    description: 'Cheesecake with fresh berries and mint for dessert',
    sales: 632,
    stock: 20,
  },
  {
    id: 16,
    asunto: 'Merveilleux',
    img: '/assets/img/merveilleux-thumb.jpg',
    category: 'Cakes',
    fecha_creacion: '18.02.2018',
    status: 'ON HOLD',
    statusColor: 'primary',
    description: 'Chocolate cake with mascarpone',
    sales: 621,
    stock: 6,
  },
  {
    id: 17,
    asunto: 'Fruitcake',
    img: '/assets/img/fruitcake-thumb.jpg',
    category: 'Cakes',
    fecha_creacion: '12.01.2019',
    status: 'PROCESSED',
    statusColor: 'secondary',
    description: 'Chocolate cake with berries',
    sales: 595,
    stock: 17,
  },
  {
    id: 18,
    asunto: 'Bebinca',
    img: '/assets/img/bebinca-thumb.jpg',
    category: 'Cakes',
    fecha_creacion: '04.02.2019',
    status: 'PROCESSED',
    statusColor: 'secondary',
    description: 'Homemade cheesecake with fresh berries and mint',
    sales: 574,
    stock: 16,
  },
  {
    id: 19,
    asunto: 'Cremeschnitte',
    img: '/assets/img/cremeschnitte-thumb.jpg',
    category: 'Desserts',
    fecha_creacion: '04.03.2018',
    status: 'ON HOLD',
    statusColor: 'primary',
    description: 'Cheesecake with chocolate cookies and Cream biscuits',
    sales: 562,
    stock: 9,
  },
  {
    id: 20,
    asunto: 'Soufflé',
    img: '/assets/img/souffle-thumb.jpg',
    category: 'Cupcakes',
    fecha_creacion: '16.01.2018',
    status: 'ON HOLD',
    statusColor: 'primary',
    description: 'Wedding cake with flowers Macarons and blueberries',
    sales: 524,
    stock: 14,
  },
];

export default mensajes;
